# Generated by Django 5.0.1 on 2024-01-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ManyToManyField(to='lyra.project'),
        ),
    ]
